// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/login";
    body: {
        email: string;
        password: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "user.login";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/register";
    body: {
        username: string;
        email: string;
        password: string;
    };
    response: {
        code: 200;
        information: "user.register";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
