/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    TheButton: typeof import('./src/components/ui/button/TheButton.vue')['default']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheInput: typeof import('./src/components/ui/input/TheInput.vue')['default']
    TheLoader: typeof import('./src/components/TheLoader.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheSkeleton: typeof import('./src/components/ui/skeleton/TheSkeleton.vue')['default']
    TheSonner: typeof import('./src/components/ui/sonner/TheSonner.vue')['default']
  }
}
